Removed mandatory=False from entities in MaltegoTransformRequestMessage
When parsing the following valid XML from Maltego, the 'entities' field
is actually not parsed but silently ignored, due to the fact
that it was marked optional.

Now the following code will throw an ParseError, which needs to be
fixed. To aid this, I have added a debug version of 'safedexml.py' in
the xmltools folder, which may be copied into your path, and thus output
debug info when calling the 'parse' function. This debug output is also
included at the end.

---------------------------------------------------------------------------

In [1]: import canari.maltego.message as msg

In [2]: mmsg = msg.MaltegoMessage.parse('''
<MaltegoMessage>
   <MaltegoTransformRequestMessage>
      <Entities>
         <Entity Type="Domain">
            <AdditionalFields>
               <Field Name="fqdn" DisplayName="Domain
               Name">paterva.com</Field>
            </AdditionalFields>
            <Weight>0</Weight>
            <Value>paterva.com</Value>
         </Entity>
      </Entities>
      <Limits SoftLimit="255" HardLimit="255"/>
   </MaltegoTransformRequestMessage>
</MaltegoMessage>
''')

---------------------------------------------------------------------------

ParseError                                Traceback (most recent call
last)
<ipython-input-3-346b231349d0> in <module>()
     14    </MaltegoTransformRequestMessage>
     15 </MaltegoMessage>
---> 16 ''')

/usr/local/lib/python2.7/dist-packages/safedexml/__init__.py in
parse(cls, xml)
    343             print nest(), 'self._fields:', str(self._fields)
    344             print nest(), 'fields found:', fields_found
--> 345             self._parse_children_unordered(node, self._fields,
fields_found)
    346         #  Check that all required fields have been found
    347

/usr/local/lib/python2.7/dist-packages/safedexml/__init__.py in
_parse_children_unordered(self, node, fields, fields_found)
    402                     continue
    403                 field = fields[idx]
--> 404                 res = field.parse_child_node(self, child)
    405                 if res is PARSE_DONE:
    406                     done_fields[idx] = True

/usr/local/lib/python2.7/dist-packages/safedexml/fields.pyc in
parse_child_node(self, obj, node)
    809             field.field_name = self.field_name
    810             field.model_class = self.model_class
--> 811             res = field.parse_child_node(obj, node)
    812             if res is dexml.PARSE_MORE:
    813                 raise ValueError("items in a Choice cannot
    return PARSE_MORE")

/usr/local/lib/python2.7/dist-packages/safedexml/fields.pyc in
parse_child_node(self, obj, node)
    474             return dexml.PARSE_SKIP
    475         else:
--> 476             inst = typeclass.parse(node)
    477             self.__set__(obj, inst)
    478             return dexml.PARSE_DONE

/usr/local/lib/python2.7/dist-packages/safedexml/__init__.py in
parse(cls, xml)
    351             if field.required and field not in fields_found:
    352                 err = "required field not found: '%s'"
    % (field.field_name,)
--> 353                 raise ParseError(err)
    354             field.parse_done(self)
    355         #  All done, return the instance so created

ParseError: required field not found: 'entities'

---------------------------------------------------------------------------

For reference, I have added some debug output from safedexml, which may
help to diagnose the issue.

It is seen that when it constructs the class
MaltegoTransformRequestMessage, then it goes straight to creating the
Limits class.

---------------------------------------------------------------------------

 parse(....) ------------------------------------------------------------------------------------
        Constructing class: MaltegoMessage
        Generating node from XML: '\n<MaltegoMessage>\n   <MaltegoTransformRequestMessage>\n      <Entities>\n         <Entity Type="Domain">\n            <AdditionalFields>\n               <Field Name="fqdn" DisplayName="Domain Name">paterva.com</Field>\n            </AdditionalFields>\n            <Weight>0</Weight>\n            <Value>paterva.com</Value>\n         </Entity>\n      </Entities>\n      <Limits SoftLimit="255" HardLimit="255"/>\n   </MaltegoTransformRequestMessage>\n</MaltegoMessage>\n'
        node: <DOM Element: MaltegoMessage at 0x7f156a955290>
        attrs: []
        Current node has the following defined fields:
                field: <safedexml.fields.Choice object at 0x7f156a9580d0> (tagname: None) (attrname: None) (field name: message) (model class: <class 'canari.maltego.message.MaltegoMessage'>)
                         Has unused_attrs: []
        parsing order_sensitive = True
        parse(....) ------------------------------------------------------------------------------------
                Constructing class: MaltegoTransformRequestMessage
                Generating node from XML: <DOM Element: MaltegoTransformRequestMessage at 0x7f156a955368>
                node: <DOM Element: MaltegoTransformRequestMessage at 0x7f156a955368>
                attrs: []
                Current node has the following defined fields:
                        field: <safedexml.fields.List object at 0x7f156a94ea50> (tagname: Entities) (attrname: None) (field name: entities) (model class: <class 'canari.maltego.message.MaltegoTransformRequestMessage'>)
                                 Has unused_attrs: []
                        field: <safedexml.fields.Dict object at 0x7f156a94eed0> (tagname: TransformFields) (attrname: None) (field name: parameters) (model class: <class 'canari.maltego.message.MaltegoTransformRequestMessage'>)
                                 Has unused_attrs: []
                        field: <safedexml.fields.Model object at 0x7f156a94ef50> (tagname: None) (attrname: None) (field name: limits) (model class: <class 'canari.maltego.message.MaltegoTransformRequestMessage'>)
                                 Has unused_attrs: []
                parsing order_sensitive = True
                parse(....) ------------------------------------------------------------------------------------
                        Constructing class: Limits
                        Generating node from XML: <DOM Element: Limits at 0x7f156a955e18>
                        node: <DOM Element: Limits at 0x7f156a955e18>
                        attrs: [<xml.dom.minidom.Attr instance at 0x7f156a955ea8>, <xml.dom.minidom.Attr instance at 0x7f156a955f80>]
                        Current node has the following defined fields:
                                field: <safedexml.fields.Integer object at 0x7f156a940d90> (tagname: None) (attrname: SoftLimit) (field name: soft) (model class: <class 'canari.maltego.message.Limits'>)
                                         Has unused_attrs: [<xml.dom.minidom.Attr instance at 0x7f156a955f80>]
                                         adding field to list of found
                                field: <safedexml.fields.Integer object at 0x7f156a940dd0> (tagname: None) (attrname: HardLimit) (field name: hard) (model class: <class 'canari.maltego.message.Limits'>)
                                         Has unused_attrs: []
                                         adding field to list of found
                        parsing order_sensitive = True
                        parse() check that required fields have been found
                                 looping field: <safedexml.fields.Integer object at 0x7f156a940d90>
                                 looping field: <safedexml.fields.Integer object at 0x7f156a940dd0>
                        Created: Limits
                parse(....) ----------------------------------------- END --------------------------------------
                parse() check that required fields have been found
                         looping field: <safedexml.fields.List object at 0x7f156a94ea50>
ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid
The error message is: ('EOF in multi-line string', (1, 0))

---------------------------------------------------------------------------